# -----------------------------------------------------
# General window decoration
# name: "Rounding All Blur No Shadows"
# -----------------------------------------------------


decoration {
    rounding = 8 # Un redondeado medio queda mejor con bordes finos
    active_opacity = 1.0
    inactive_opacity = 0.8 # Ayuda a distinguir ventanas sin necesidad de bordes

    blur {
        enabled = true
        size = 6      # Un poco más de blur para compensar la falta de bordes
        passes = 3
        new_optimizations = on
        ignore_opacity = true
        xray = false  # Desactiva xray para un look más limpio
    }

    shadow {
        enabled = false

    }

}
