# My Hyprland configuration - @rubenConf
#      , .-.-,_,
#      )`-.>'` (
#     /     `\  |
#     |       | |
#      \     / /
#      `=(\ /.=`
#       `-;`.-'
#         `)|     ,
#          ||  .-'|
#        ,_||  \_,/
#  ,      \|| .'
#  |\|\  , ||/
# ,_\` |/| |Y_,
#  '-.'-._\||/
#     >_.-`Y|
#     ` .-"||"-.
#       \'----'/
#        |:.  |
#        |::. |
#       /::::  \
#     .:::'     '.
#    /:::         \
#   ;:::'          ;
#   |:::           |
#   |:::           |
#   |:::           |
#   ;:::           ;
#   \:::.          /
#jgs ':::..      .'
#     `""-----""`
#
# -----------------------------------------------------
#
# Art from: Joan G Stark (Spunk)
# https://www.asciiart.eu/art/03eac5a5215f1aa4
#
# Based on ML4W dotfiles

# -----------------------------------------------------
# Monitor
# -----------------------------------------------------
source = ~/.config/hypr/conf/monitor.conf

# -----------------------------------------------------
# Cursor
# -----------------------------------------------------
source = ~/.config/hypr/conf/cursor.conf

# -----------------------------------------------------
# Keyboard
# -----------------------------------------------------
source = ~/.config/hypr/conf/keyboard.conf

# -----------------------------------------------------
# Load color file
# -----------------------------------------------------
source = ~/.config/hypr/colors.conf
$primary = $primary
$on_surface = $on_surface

# -----------------------------------------------------
# Autostart
# -----------------------------------------------------
source = ~/.config/hypr/conf/autostart.conf

# -----------------------------------------------------
# Load configuration files
# -----------------------------------------------------
source = ~/.config/hypr/conf/window.conf
source = ~/.config/hypr/conf/decoration.conf
source = ~/.config/hypr/conf/layout.conf
source = ~/.config/hypr/conf/workspace.conf
source = ~/.config/hypr/conf/misc.conf
source = ~/.config/hypr/conf/keybinding.conf
source = ~/.config/hypr/conf/windowrule.conf

# -----------------------------------------------------
# Animation
# -----------------------------------------------------
source = ~/.config/hypr/conf/animation.conf

# -----------------------------------------------------
# Environment for xdg-desktop-portal-hyprland
# -----------------------------------------------------
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# -----------------------------------------------------
# old ML4W Configuration stuff
# -----------------------------------------------------
source = ~/.config/hypr/conf/rules.conf

# -----------------------------------------------------
# Custom
# -----------------------------------------------------
source = ~/.config/hypr/conf/custom.conf
